/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AppRouteImport } from "./routes/_app"
import { Route as MarketingRouteImport } from "./routes/_marketing"
import { Route as AppProfileRouteImport } from "./routes/_app/profile"
import { Route as MarketingIndexRouteImport } from "./routes/_marketing/index"
import { Route as MarketingAboutRouteImport } from "./routes/_marketing/about"
import { Route as MarketingContactRouteImport } from "./routes/_marketing/contact"
import { Route as MarketingLoginRouteImport } from "./routes/_marketing/login"
import { Route as MarketingSignupRouteImport } from "./routes/_marketing/signup"

const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: "/_marketing",
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AppRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingLoginRoute = MarketingLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingSignupRoute = MarketingSignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => MarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof MarketingIndexRoute
  "/profile": typeof AppProfileRoute
  "/about": typeof MarketingAboutRoute
  "/contact": typeof MarketingContactRoute
  "/login": typeof MarketingLoginRoute
  "/signup": typeof MarketingSignupRoute
}
export interface FileRoutesByTo {
  "/": typeof MarketingIndexRoute
  "/profile": typeof AppProfileRoute
  "/about": typeof MarketingAboutRoute
  "/contact": typeof MarketingContactRoute
  "/login": typeof MarketingLoginRoute
  "/signup": typeof MarketingSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_app": typeof AppRouteWithChildren
  "/_marketing": typeof MarketingRouteWithChildren
  "/_app/profile": typeof AppProfileRoute
  "/_marketing/about": typeof MarketingAboutRoute
  "/_marketing/contact": typeof MarketingContactRoute
  "/_marketing/login": typeof MarketingLoginRoute
  "/_marketing/signup": typeof MarketingSignupRoute
  "/_marketing/": typeof MarketingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/profile" | "/about" | "/contact" | "/login" | "/signup"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/profile" | "/about" | "/contact" | "/login" | "/signup"
  id:
    | "__root__"
    | "/_app"
    | "/_marketing"
    | "/_app/profile"
    | "/_marketing/about"
    | "/_marketing/contact"
    | "/_marketing/login"
    | "/_marketing/signup"
    | "/_marketing/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_marketing": {
      id: "/_marketing"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/profile": {
      id: "/_app/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    "/_marketing/": {
      id: "/_marketing/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    "/_marketing/about": {
      id: "/_marketing/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    "/_marketing/contact": {
      id: "/_marketing/contact"
      path: "/contact"
      fullPath: "/contact"
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    "/_marketing/login": {
      id: "/_marketing/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof MarketingLoginRouteImport
      parentRoute: typeof MarketingRoute
    }
    "/_marketing/signup": {
      id: "/_marketing/signup"
      path: "/signup"
      fullPath: "/signup"
      preLoaderRoute: typeof MarketingSignupRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingLoginRoute: typeof MarketingLoginRoute
  MarketingSignupRoute: typeof MarketingSignupRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingLoginRoute: MarketingLoginRoute,
  MarketingSignupRoute: MarketingSignupRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
